print("Escribe un número de telefono según la extensión codigo de país-número-extension")
numeroDeTelf = str(input())
index1 = int(numeroDeTelf.index("-") + 1)
temp = str(numeroDeTelf[index1:numeroDeTelf.__len__()])
index2 = int(temp.index("-"))
print(temp[0:index2])